//! HTTP/1.1 request framing for the echo server.
//!
//! [`HttpProtocol`] plugs HTTP into the generic [`StreamEchoServer`] read/echo
//! loop. The loop calls [`StreamProtocol::read`] and writes whatever it gets
//! back with [`StreamProtocol::write`]. [`HttpStream`] handles HTTP framing
//! internally, so that loop works unchanged:
//!
//! * `read` buffers the request head, validates it, and returns **only body
//!   bytes** (bounded by `Content-Length`). It returns `Ok(0)` once the body has
//!   been fully returned, or after it has sent an error response. Either way the
//!   generic loop then closes the connection.
//! * `write` sends the `200 OK` response head right before the first echoed
//!   body chunk, then streams the body.
//! * Empty bodies and error responses are sent from inside `read`, because the
//!   generic loop never calls `write` for a zero-length read.
//! * For rate limiting, HTTP frames its own requests
//!   ([`StreamProtocol::FRAMED_REQUESTS`]): the server reads the head with
//!   [`StreamProtocol::begin_request`] and counts it as one request. Rejected
//!   requests and connections are answered by [`StreamProtocol::reject`] with
//!   `429 Too Many Requests`.
//!
//! See the [`crate::http`] module docs for the exact HTTP semantics.
//!
//! [`StreamEchoServer`]: crate::stream::StreamEchoServer

use super::config::HttpConfig;
use crate::stream::{RejectReason, StreamConfig, StreamProtocol};

use async_trait::async_trait;
use std::io;
use std::net::SocketAddr;
use std::sync::Arc;
use std::time::Duration;
use tokio::io::{AsyncReadExt, AsyncWriteExt};
use tokio::net::{TcpListener, TcpStream};
use tracing::debug;

/// Maximum size in bytes of the request head (request line and headers,
/// including the terminating blank line). Larger heads get
/// `431 Request Header Fields Too Large`.
pub const MAX_HEADER_BYTES: usize = 8 * 1024;

/// Maximum number of request headers. Requests with more headers get
/// `400 Bad Request`.
pub const MAX_HEADERS: usize = 32;

/// Default maximum request body size (1 MiB). See [`HttpConfig::max_body_size`].
pub const DEFAULT_MAX_BODY_SIZE: usize = 1024 * 1024;

/// How long to keep draining unread input after the response is sent, before
/// closing. Without this, closing with unread data can send a TCP RST that
/// makes the peer drop the response.
const LINGER_TIMEOUT: Duration = Duration::from_millis(500);

/// Maximum number of bytes to discard while lingering.
const LINGER_MAX_BYTES: usize = 256 * 1024;

/// Content type used for error responses generated by the server.
const ERROR_CONTENT_TYPE: &str = "text/plain; charset=utf-8";

/// How long to wait for the request head of a connection rejected by the
/// accept rate limit, before answering `429` anyway.
const REJECT_HEAD_TIMEOUT: Duration = Duration::from_millis(500);

/// HTTP protocol implementation for the echo server.
///
/// Accepts only `POST` requests and echoes the request body back in a
/// `200 OK` response. Each connection serves exactly one request, then closes.
/// See the [`crate::http`] module docs for the full semantics.
///
/// HTTP-specific settings ([`HttpConfig::server_name`],
/// [`HttpConfig::default_content_type`], [`HttpConfig::max_body_size`]) are
/// applied when the server runs as an [`HttpEchoServer`](crate::http::HttpEchoServer).
/// A plain `StreamEchoServer<HttpProtocol>` uses the [`HttpConfig::default`]
/// values for those settings.
pub struct HttpProtocol;

/// Errors produced by [`HttpProtocol`].
///
/// Protocol violations by the client (malformed requests, disallowed methods,
/// oversized bodies, ...) are **not** reported as errors. They are answered
/// with the matching HTTP error response, and the connection is closed
/// cleanly.
#[derive(Debug, thiserror::Error)]
pub enum HttpProtocolError {
    /// Underlying socket I/O failed.
    #[error("IO error: {0}")]
    Io(#[from] io::Error),
    /// The HTTP message could not be parsed.
    #[error("HTTP parsing error: {0}")]
    HttpParse(String),
    /// The stream was used in a way that does not fit the HTTP exchange, e.g.
    /// writing more bytes than the request body contained.
    #[error("Invalid request: {0}")]
    InvalidRequest(String),
    /// The peer closed the connection before a complete message arrived.
    #[error("Incomplete request")]
    IncompleteRequest,
    /// Binding the listener failed. Carries the [`EchoError`](crate::EchoError)
    /// from the TCP bind unchanged (e.g. [`EchoError::FdInheritance`] or
    /// [`EchoError::Config`]), and converts back into it as is.
    ///
    /// [`EchoError::FdInheritance`]: crate::EchoError::FdInheritance
    /// [`EchoError::Config`]: crate::EchoError::Config
    #[error(transparent)]
    Bind(crate::EchoError),
}

/// HTTP-specific settings carried by every accepted [`HttpStream`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct HttpSettings {
    /// Value of the `Server` response header (omitted if `None`).
    pub(crate) server_name: Option<String>,
    /// Value of the `Content-Type` header on `200` responses (omitted if `None`).
    pub(crate) content_type: Option<String>,
    /// Maximum accepted `Content-Length`.
    pub(crate) max_body_size: usize,
}

impl From<&HttpConfig> for HttpSettings {
    fn from(config: &HttpConfig) -> Self {
        Self {
            server_name: config.server_name.clone(),
            content_type: config.default_content_type.clone(),
            max_body_size: config.max_body_size,
        }
    }
}

tokio::task_local! {
    /// Settings for streams accepted by the current server task. Set by
    /// `HttpEchoServer::run`, read by `HttpProtocol::accept`.
    pub(crate) static HTTP_SETTINGS: Arc<HttpSettings>;
}

impl HttpSettings {
    /// Returns the settings of the enclosing `HttpEchoServer`, or defaults.
    fn current() -> Arc<Self> {
        HTTP_SETTINGS
            .try_with(Arc::clone)
            .unwrap_or_else(|_| Arc::new(Self::from(&HttpConfig::default())))
    }
}

/// An error response that rejects the request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct Rejection {
    pub(crate) status: u16,
    pub(crate) reason: &'static str,
    pub(crate) message: String,
    /// Whether to include `Allow: POST` (for `405`).
    pub(crate) allow_post: bool,
    /// Value of the `Retry-After` header in seconds (for `429`).
    pub(crate) retry_after_secs: Option<u64>,
}

impl Rejection {
    fn new(status: u16, reason: &'static str, message: impl Into<String>) -> Self {
        Self {
            status,
            reason,
            message: message.into(),
            allow_post: false,
            retry_after_secs: None,
        }
    }

    fn bad_request(message: impl Into<String>) -> Self {
        Self::new(400, "Bad Request", message)
    }

    /// `429 Too Many Requests`. `Retry-After` is `retry_after` in whole
    /// seconds, rounded up, and at least 1.
    pub(crate) fn too_many_requests(retry_after: Duration) -> Self {
        let secs = retry_after.as_secs() + u64::from(retry_after.subsec_nanos() > 0);
        let secs = secs.max(1);
        Self {
            retry_after_secs: Some(secs),
            ..Self::new(
                429,
                "Too Many Requests",
                format!("Rate limit exceeded. Retry after {secs} s."),
            )
        }
    }

    /// The headers this rejection adds to the response head.
    fn extra_headers(&self) -> Vec<(&'static str, String)> {
        let mut headers = Vec::new();
        if self.allow_post {
            headers.push(("Allow", "POST".to_string()));
        }
        if let Some(secs) = self.retry_after_secs {
            headers.push(("Retry-After", secs.to_string()));
        }
        headers
    }
}

/// A validated request head.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct RequestHead {
    /// Length of the head in bytes, including the terminating blank line.
    pub(crate) head_len: usize,
    /// Declared body length (`0` if `Content-Length` is absent).
    pub(crate) content_length: usize,
    /// Whether the client sent `Expect: 100-continue` on HTTP/1.1.
    pub(crate) expect_continue: bool,
}

/// Result of trying to parse a (possibly partial) request head.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum HeadOutcome {
    /// More bytes are needed.
    Partial,
    /// The head is complete and acceptable.
    Request(RequestHead),
    /// The request must be rejected with an error response.
    Reject(Rejection),
}

/// Parses and validates a request head from the start of `buf`.
///
/// `buf` must hold at most [`MAX_HEADER_BYTES`] bytes. If the head is still
/// incomplete once that much has been read, the request is rejected with 431.
pub(crate) fn parse_head(buf: &[u8], max_body_size: usize) -> HeadOutcome {
    let mut headers = [httparse::EMPTY_HEADER; MAX_HEADERS];
    let mut req = httparse::Request::new(&mut headers);

    let head_len = match req.parse(buf) {
        Ok(httparse::Status::Complete(len)) => len,
        Ok(httparse::Status::Partial) => {
            return if buf.len() >= MAX_HEADER_BYTES {
                HeadOutcome::Reject(Rejection::new(
                    431,
                    "Request Header Fields Too Large",
                    format!("Request head exceeds {MAX_HEADER_BYTES} bytes."),
                ))
            } else {
                HeadOutcome::Partial
            };
        }
        Err(httparse::Error::TooManyHeaders) => {
            return HeadOutcome::Reject(Rejection::bad_request(format!(
                "Too many headers (maximum is {MAX_HEADERS})."
            )));
        }
        Err(e) => {
            return HeadOutcome::Reject(Rejection::bad_request(format!("Malformed request: {e}.")));
        }
    };

    // A complete parse always yields a method.
    let method = req.method.unwrap_or_default();
    if method != "POST" {
        return HeadOutcome::Reject(Rejection {
            allow_post: true,
            ..Rejection::new(
                405,
                "Method Not Allowed",
                format!("Method {method} not allowed. Only POST requests are accepted."),
            )
        });
    }

    let mut content_length: Option<usize> = None;
    let mut transfer_encoding = false;
    let mut expect_continue = false;

    for header in req.headers.iter() {
        if header.name.eq_ignore_ascii_case("transfer-encoding") {
            transfer_encoding = true;
        } else if header.name.eq_ignore_ascii_case("content-length") {
            let Some(value) = parse_content_length(header.value) else {
                return HeadOutcome::Reject(Rejection::bad_request("Invalid Content-Length."));
            };
            if content_length.is_some_and(|existing| existing != value) {
                return HeadOutcome::Reject(Rejection::bad_request(
                    "Conflicting Content-Length headers.",
                ));
            }
            content_length = Some(value);
        } else if header.name.eq_ignore_ascii_case("expect") {
            expect_continue = header
                .value
                .trim_ascii()
                .eq_ignore_ascii_case(b"100-continue");
        }
    }

    if transfer_encoding {
        return HeadOutcome::Reject(Rejection::new(
            501,
            "Not Implemented",
            "Transfer-Encoding is not supported; send the body with Content-Length.",
        ));
    }

    let content_length = content_length.unwrap_or(0);
    if content_length > max_body_size {
        return HeadOutcome::Reject(Rejection::new(
            413,
            "Content Too Large",
            format!("Request body exceeds the maximum of {max_body_size} bytes."),
        ));
    }

    HeadOutcome::Request(RequestHead {
        head_len,
        content_length,
        expect_continue: expect_continue && req.version == Some(1),
    })
}

/// Parses a `Content-Length` value: ASCII digits only, optional surrounding
/// whitespace, no sign, and no list syntax.
pub(crate) fn parse_content_length(value: &[u8]) -> Option<usize> {
    let value = value.trim_ascii();
    if value.is_empty() || !value.iter().all(u8::is_ascii_digit) {
        return None;
    }
    std::str::from_utf8(value).ok()?.parse().ok()
}

/// Builds a response head ending with the blank line. `extra_headers` are
/// emitted after `Server`, in order.
pub(crate) fn response_head(
    status: u16,
    reason: &str,
    server_name: Option<&str>,
    content_type: Option<&str>,
    content_length: usize,
    extra_headers: &[(&str, String)],
) -> Vec<u8> {
    use std::fmt::Write;

    let mut head = String::with_capacity(160);
    // Writing to a String cannot fail.
    let _ = write!(head, "HTTP/1.1 {status} {reason}\r\n");
    if let Some(server) = server_name {
        let _ = write!(head, "Server: {server}\r\n");
    }
    for (name, value) in extra_headers {
        let _ = write!(head, "{name}: {value}\r\n");
    }
    if let Some(content_type) = content_type {
        let _ = write!(head, "Content-Type: {content_type}\r\n");
    }
    let _ = write!(head, "Content-Length: {content_length}\r\n");
    head.push_str("Connection: close\r\n\r\n");
    head.into_bytes()
}

/// Progress through the request body.
#[derive(Debug, Clone, Copy)]
struct BodyState {
    content_length: usize,
    /// Body bytes not yet returned from `read`.
    to_read: usize,
    /// Body bytes not yet echoed through `write`.
    to_write: usize,
    /// Whether the `200 OK` head has been sent.
    head_sent: bool,
}

#[derive(Debug, Clone, Copy)]
enum State {
    /// Reading the request head.
    Head,
    /// Returning body bytes from `read` and echoing them from `write`.
    Body(BodyState),
    /// The head was complete but invalid; the next `read` sends the error
    /// response held in `HttpStream::invalid`.
    Invalid,
    /// The response is complete (or the request was rejected); `read`
    /// returns `Ok(0)`.
    Done,
}

/// A TCP connection that carries a single HTTP/1.1 request/response exchange.
///
/// This is the [`StreamProtocol::Stream`] type of [`HttpProtocol`]. It
/// buffers and validates the request head internally. To callers, its body
/// looks like a plain byte stream, and it frames the echoed bytes as an HTTP
/// response.
pub struct HttpStream {
    inner: TcpStream,
    settings: Arc<HttpSettings>,
    /// Request head bytes while in `State::Head`. Afterwards, the body bytes
    /// that arrived together with the head.
    buf: Vec<u8>,
    /// Cursor into `buf` for body bytes not yet returned.
    buf_pos: usize,
    state: State,
    /// The error response to send in `State::Invalid`.
    invalid: Option<Rejection>,
}

impl HttpStream {
    fn new(inner: TcpStream, settings: Arc<HttpSettings>) -> Self {
        Self {
            inner,
            settings,
            buf: Vec::new(),
            buf_pos: 0,
            state: State::Head,
            invalid: None,
        }
    }

    /// Reads until the request head is complete. Then switches to
    /// `State::Body`, or to `State::Invalid` with the error response to send.
    /// Switches to `State::Done` if the peer closes first.
    async fn read_head(&mut self) -> Result<(), HttpProtocolError> {
        loop {
            if !self.buf.is_empty() {
                match parse_head(&self.buf, self.settings.max_body_size) {
                    HeadOutcome::Partial => {}
                    HeadOutcome::Reject(rejection) => {
                        // Answered by the next `read`, unless the request is
                        // rate limited first (then it gets a 429 instead).
                        self.invalid = Some(rejection);
                        self.state = State::Invalid;
                        return Ok(());
                    }
                    HeadOutcome::Request(head) => return self.start_body(head).await,
                }
            }

            let filled = self.buf.len();
            self.buf.resize(MAX_HEADER_BYTES, 0);
            let n = match self.inner.read(&mut self.buf[filled..]).await {
                Ok(n) => n,
                Err(e) => {
                    self.buf.truncate(filled);
                    return Err(e.into());
                }
            };
            self.buf.truncate(filled + n);
            if n == 0 {
                if filled > 0 {
                    debug!(
                        bytes = filled,
                        "Client closed connection before completing the request head"
                    );
                }
                self.state = State::Done;
                return Ok(());
            }
        }
    }

    async fn start_body(&mut self, head: RequestHead) -> Result<(), HttpProtocolError> {
        // Keep only the body bytes that arrived together with the head. Bytes
        // past Content-Length (e.g. a pipelined request) are discarded,
        // because only one request is served per connection.
        self.buf.drain(..head.head_len);
        self.buf.truncate(head.content_length);
        self.buf_pos = 0;
        self.state = State::Body(BodyState {
            content_length: head.content_length,
            to_read: head.content_length,
            to_write: head.content_length,
            head_sent: false,
        });

        if head.expect_continue && head.content_length > self.buf.len() {
            self.inner
                .write_all(b"HTTP/1.1 100 Continue\r\n\r\n")
                .await?;
            self.inner.flush().await?;
        }
        Ok(())
    }

    /// Returns the next body bytes: first those already buffered, then those
    /// read from the socket.
    async fn read_body(
        &mut self,
        mut body: BodyState,
        buffer: &mut [u8],
    ) -> Result<usize, HttpProtocolError> {
        if body.to_read == 0 {
            if !body.head_sent {
                // Only reachable for an empty body. Non-empty bodies have
                // their head sent by `write`.
                let head = self.ok_head(body.content_length);
                self.inner.write_all(&head).await?;
            }
            self.finish().await;
            return Ok(0);
        }

        let limit = buffer.len().min(body.to_read);
        let n = if self.buf_pos < self.buf.len() {
            let n = limit.min(self.buf.len() - self.buf_pos);
            buffer[..n].copy_from_slice(&self.buf[self.buf_pos..self.buf_pos + n]);
            self.buf_pos += n;
            n
        } else {
            let n = self.inner.read(&mut buffer[..limit]).await?;
            if n == 0 {
                debug!(
                    missing = body.to_read,
                    "Client closed connection before sending the full body"
                );
                self.state = State::Done;
                return Ok(0);
            }
            n
        };

        body.to_read -= n;
        self.state = State::Body(body);
        Ok(n)
    }

    fn ok_head(&self, content_length: usize) -> Vec<u8> {
        response_head(
            200,
            "OK",
            self.settings.server_name.as_deref(),
            self.settings.content_type.as_deref(),
            content_length,
            &[],
        )
    }

    /// Sends an error response, then closes gracefully.
    async fn reject(&mut self, rejection: &Rejection) {
        debug!(
            status = rejection.status,
            reason = rejection.reason,
            message = %rejection.message,
            "Rejecting HTTP request"
        );
        let mut response = response_head(
            rejection.status,
            rejection.reason,
            self.settings.server_name.as_deref(),
            Some(ERROR_CONTENT_TYPE),
            rejection.message.len(),
            &rejection.extra_headers(),
        );
        response.extend_from_slice(rejection.message.as_bytes());
        if let Err(e) = self.inner.write_all(&response).await {
            debug!(error = %e, "Failed to send HTTP error response");
        }
        self.finish().await;
    }

    /// Answers `429 Too Many Requests`, then closes gracefully.
    ///
    /// If the request head has not been read yet (a connection rejected by
    /// the accept rate limit), it is read first, for at most
    /// [`REJECT_HEAD_TIMEOUT`]. Otherwise the client could still be sending
    /// it when we close, and the resulting RST could discard the response.
    /// Any body is drained by the linger in [`finish`](Self::finish).
    async fn reject_rate_limited(&mut self, retry_after: Duration) {
        if matches!(self.state, State::Done) {
            // A response was already sent.
            return;
        }
        if matches!(self.state, State::Head) {
            let _ = tokio::time::timeout(REJECT_HEAD_TIMEOUT, self.read_head_unchecked()).await;
        }
        self.invalid = None;
        self.reject(&Rejection::too_many_requests(retry_after))
            .await;
    }

    /// Reads into `buf` until it holds a complete (or unparsable) request
    /// head, the head limit is reached, or the peer stops sending. The head
    /// is not acted upon.
    async fn read_head_unchecked(&mut self) {
        let mut scratch = [0u8; 4096];
        while self.buf.len() < MAX_HEADER_BYTES
            && matches!(
                parse_head(&self.buf, self.settings.max_body_size),
                HeadOutcome::Partial
            )
        {
            match self.inner.read(&mut scratch).await {
                Ok(0) | Err(_) => return,
                Ok(n) => self.buf.extend_from_slice(&scratch[..n]),
            }
        }
    }

    /// Closes our side of the connection, then briefly drains unread input.
    /// This keeps the response from being lost to a TCP RST.
    async fn finish(&mut self) {
        self.state = State::Done;
        self.buf = Vec::new();
        if self.inner.shutdown().await.is_err() {
            return;
        }
        let drain = async {
            let mut scratch = [0u8; 4096];
            let mut discarded = 0;
            while discarded < LINGER_MAX_BYTES {
                match self.inner.read(&mut scratch).await {
                    Ok(0) | Err(_) => break,
                    Ok(n) => discarded += n,
                }
            }
        };
        let _ = tokio::time::timeout(LINGER_TIMEOUT, drain).await;
    }
}

#[async_trait]
impl StreamProtocol for HttpProtocol {
    type Error = HttpProtocolError;
    type Listener = TcpListener;
    type Stream = HttpStream;

    async fn bind(config: &StreamConfig) -> std::result::Result<Self::Listener, Self::Error> {
        // Delegate to TCP so HTTP gets the same bind strategy / FD inheritance,
        // and the same bind errors.
        <crate::tcp::TcpProtocol as StreamProtocol>::bind(config)
            .await
            .map_err(HttpProtocolError::Bind)
    }

    async fn bind_with_inheritance(
        config: &StreamConfig,
        fd_config: &crate::network::FdInheritanceConfig,
    ) -> std::result::Result<Self::Listener, Self::Error> {
        <crate::tcp::TcpProtocol as StreamProtocol>::bind_with_inheritance(config, fd_config)
            .await
            .map_err(HttpProtocolError::Bind)
    }

    async fn accept(
        listener: &mut Self::Listener,
    ) -> std::result::Result<(Self::Stream, SocketAddr), Self::Error> {
        let (stream, addr) = listener.accept().await.map_err(HttpProtocolError::Io)?;
        Ok((HttpStream::new(stream, HttpSettings::current()), addr))
    }

    /// Opens a TCP connection wrapped with **server-side** framing.
    ///
    /// This exists only to satisfy [`StreamProtocol`]. To talk to an HTTP echo
    /// server, use [`HttpEchoClient`](crate::http::HttpEchoClient).
    async fn connect(addr: SocketAddr) -> std::result::Result<Self::Stream, Self::Error> {
        let stream = TcpStream::connect(addr)
            .await
            .map_err(HttpProtocolError::Io)?;
        Ok(HttpStream::new(stream, HttpSettings::current()))
    }

    /// Returns request body bytes.
    ///
    /// Buffers and validates the request head first. Returns `Ok(0)` after the
    /// whole body has been returned, or after an error response was sent.
    async fn read(
        stream: &mut Self::Stream,
        buffer: &mut [u8],
    ) -> std::result::Result<usize, Self::Error> {
        loop {
            match stream.state {
                State::Done => return Ok(0),
                State::Head => stream.read_head().await?,
                State::Body(body) => return stream.read_body(body, buffer).await,
                State::Invalid => {
                    if let Some(rejection) = stream.invalid.take() {
                        stream.reject(&rejection).await;
                    }
                    stream.state = State::Done;
                }
            }
        }
    }

    /// Echoes body bytes previously returned by `read`.
    ///
    /// The first call sends the `200 OK` response head. Writing more bytes
    /// than the request's `Content-Length`, or writing outside a request
    /// body, is an [`HttpProtocolError::InvalidRequest`].
    async fn write(stream: &mut Self::Stream, data: &[u8]) -> std::result::Result<(), Self::Error> {
        let State::Body(mut body) = stream.state else {
            return Err(HttpProtocolError::InvalidRequest(
                "no HTTP request body is being echoed".to_string(),
            ));
        };
        if data.len() > body.to_write {
            return Err(HttpProtocolError::InvalidRequest(format!(
                "echo of {} bytes exceeds the {} remaining body bytes",
                data.len(),
                body.to_write
            )));
        }

        if body.head_sent {
            stream.inner.write_all(data).await?;
        } else {
            let mut out = stream.ok_head(body.content_length);
            out.extend_from_slice(data);
            stream.inner.write_all(&out).await?;
            body.head_sent = true;
        }
        body.to_write -= data.len();
        stream.state = State::Body(body);
        Ok(())
    }

    async fn flush(stream: &mut Self::Stream) -> std::result::Result<(), Self::Error> {
        stream.inner.flush().await.map_err(HttpProtocolError::Io)
    }

    fn map_io_error(err: io::Error) -> Self::Error {
        HttpProtocolError::Io(err)
    }

    /// Each connection carries one request, framed by its head.
    const FRAMED_REQUESTS: bool = true;

    /// Reads and validates the request head.
    ///
    /// Returns `Ok(true)` once a complete head has arrived, and `Ok(false)` if
    /// the peer closed the connection first. An invalid request also counts
    /// as a request: its error response (`400`, `405`, ...) is sent by the
    /// following `read`, or replaced by `429` if the request is rate limited.
    async fn begin_request(stream: &mut Self::Stream) -> std::result::Result<bool, Self::Error> {
        while matches!(stream.state, State::Head) {
            stream.read_head().await?;
        }
        Ok(matches!(stream.state, State::Body(_) | State::Invalid))
    }

    /// Answers `429 Too Many Requests` with `Retry-After` (whole seconds,
    /// rounded up, at least 1) and `Connection: close`, then closes
    /// gracefully.
    ///
    /// For a connection rejected by the accept rate limit the request head is
    /// read first (bounded by a short timeout), and any body is drained
    /// briefly after the response, so the client is not sent an RST that
    /// would discard the `429`.
    async fn reject(
        stream: &mut Self::Stream,
        _reason: RejectReason,
        retry_after: Duration,
    ) -> std::result::Result<(), Self::Error> {
        stream.reject_rate_limited(retry_after).await;
        Ok(())
    }
}
